name: Test Signing Install

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        BuildType: [Release]
        Arch: [x64] # Arm64

    defaults:
      run:
        shell: cmd

    env:
      ARTIFACT: QGroundControl-installer.exe
      PACKAGE: QGroundControl-installer
      QT_VERSION: 6.8.3
      GST_VERSION: 1.22.12

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          fetch-tags: false

 

    ########################


      - name: Download KMS CNG
        run: |
          echo "runner.temp ${{ runner.temp }}"
          curl -L -o ${{ runner.temp }}\shadow_build_dir\kms\kmscng.zip --create-dirs ${{ vars.KMS_CNG_PROVIDER_DOWNLOAD }}

      - name: Verify KMS CNG
        shell: pwsh
        run: |
          $expectedHash = "${{ vars.KMS_CNG_PROVIDER_DOWNLOAD_SHA }}"
          $currentHash = (Get-FileHash -Path "${{ runner.temp }}\shadow_build_dir\kms\kmscng.zip" -Algorithm SHA256).Hash

          if ($currentHash -eq $expectedHash) {
              Write-Host "Success: Hashes match!"
          } else {
              Write-Error "Failure: Hashes do not match. Expected: $expectedHash, Got: $currentHash"
              exit 1
          }

      - name: Unzip KMS CNG
        working-directory: ${{ runner.temp }}\shadow_build_dir\kms
        run: |
          pwd
          unzip kmscng.zip

      - name: Install KMS CNG Crypto Provider
        # Experience has shown to avoid adding "/l" (logging) options to the msiexec command that follows.
        # Doing so causes the KMS CNG install to silently fail (exit code 0), which then results in a failure
        # of the sign step (exit code 1) without obvious indication that the sign step failed as a result
        # of failure to install the KMS CNG Crypto Provider.
        working-directory: ${{ runner.temp }}/shadow_build_dir/kms
        run: |
          cd
          msiexec /package "${{ vars.KMS_CNG_MSI }}" /quiet

      - name: Authenticate to Google Cloud Platform for Code Signing
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ vars.WINDOWS_SIGNING_PROJECT_ID }}
          workload_identity_provider: ${{ vars.WINDOWS_SIGNING_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: '${{ vars.WINDOWS_SIGNING_SERVICE_ACCOUNT }}@${{ vars.WINDOWS_SIGNING_PROJECT_ID }}.iam.gserviceaccount.com'
          token_format: id_token
          id_token_audience: '${{ vars.WINDOWS_SIGNING_PROJECT_ID }}'
          id_token_include_email: true
          # The request_reason value will be injected into the "X-Goog-Request-Reason" HTTP header,
          # which in turn will appear in Google Cloud audit logs to aid in analysis/troublshooting
          # exercises.
          request_reason: ${{ github.workflow_ref }}

    #   - name: Sign MSI File
    #     run: |
    #       .\MissionPlanner\add-signtool.ps1
    #       signtool.exe sign /v /debug /fd sha256 /t ${{ vars.CODE_SIGNING_TIMESTAMP_SERVER_URL }} /f ${{ vars.CODE_SIGNING_CERT }} /csp "Google Cloud KMS Provider" /kc ${{ vars.CODE_SIGNING_PRIVATE_KEY_CONTAINER }} MissionPlanner\Msi\MissionPlanner-*.msi

    #   - name: Sign MSI File
    #     working-directory: ${{ runner.temp }}\shadow_build_dir\Release
    #     run: |
    #       .\MissionPlanner\add-signtool.ps1
    #       signtool.exe sign /v /debug /fd sha256 /t ${{ vars.CODE_SIGNING_TIMESTAMP_SERVER_URL }} /f ${{ vars.CODE_SIGNING_CERT }} /csp "Google Cloud KMS Provider" /kc ${{ vars.CODE_SIGNING_PRIVATE_KEY_CONTAINER }} MissionPlanner\Msi\MissionPlanner-*.msi

    #   - name: Create SHA from MSI File
    #     shell: bash
    #     run: |
    #       cd MissionPlanner/Msi
    #       # We can wildcard the input file name if we wish, but not the output file name.
    #       sha256sum MissionPlanner-${{ env.MP_VERSION }}.msi > MissionPlanner-${{ env.MP_VERSION }}.sha256

    #   - name: Upload artifacts
    #     if: ${{env.do_deployment == 'false'}}
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: Mission Planner Install v${{ env.MP_VERSION }}
    #       path: |
    #           MissionPlanner\Msi\MissionPlanner-${{ env.MP_VERSION }}.msi
    #           MissionPlanner\Msi\MissionPlanner-${{ env.MP_VERSION }}.sha256
    #           MissionPlanner\Msi\MissionPlanner-${{ env.MP_VERSION }}.json
    #       if-no-files-found: error

    #   - name: Authenticate to Google Cloud Platform for uploading to Cloud Storage
    #     if: ${{env.do_deployment == 'true'}}
    #     id: cloud_storage_auth
    #     uses: 'google-github-actions/auth@v2'
    #     with:
    #       project_id: ${{ vars.MSI_DEPLOYMENT_PROJECT_ID }}
    #       workload_identity_provider: ${{ vars.MSI_DEPLOYMENT_WORKLOAD_IDENTITY_PROVIDER }}
    #       service_account: '${{ vars.MSI_DEPLOYMENT_SERVICE_ACCOUNT }}@${{ vars.MSI_DEPLOYMENT_PROJECT_ID }}.iam.gserviceaccount.com'
    #       token_format: id_token
    #       id_token_audience: '${{ vars.MSI_DEPLOYMENT_PROJECT_ID }}'
    #       id_token_include_email: true
    #       # The request_reason value will be injected into the "X-Goog-Request-Reason" HTTP header,
    #       # which in turn will appear in Google Cloud audit logs to aid in analysis/troublshooting
    #       # exercises.
    #       request_reason: ${{ github.workflow_ref }}


    ########################


      - name: Sanity check release excecutable
        if: matrix.BuildType == 'Release'
        working-directory: ${{ runner.temp }}\shadow_build_dir\Release
        run: QGroundControl.exe --simple-boot-test

      - name: Install
        working-directory: ${{ runner.temp }}\shadow_build_dir
        run: cmake --install . --config ${{ matrix.BuildType }}

      - name: Upload Build File
        if: matrix.BuildType == 'Release'
        uses: ./.github/actions/upload
        with:
          artifact_name: ${{ env.ARTIFACT }}
          package_name: ${{ env.PACKAGE }}
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
